<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="AO2E2E919R2"><DocLocation><![CDATA[C:\Click And Collect\Automation\Test Scripts\TC075_ClickAndCollect_TAO_253]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[TC075_ClickAndCollect_TAO_253]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="602" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:19]]></Time>
<TimeTick>1626375859</TimeTick>
<NodeArgs eType="Replay" icon="605" nRep="8" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:19]]></Time>
<TimeTick>1626375859</TimeTick>
<NodeArgs eType="Replay" icon="605" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:23]]></Time>
<TimeTick>1626375863</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Main Menu.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:23]]></Time>
<TimeTick>1626375863</TimeTick>
<NodeArgs eType="Replay" icon="607" nRep="12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Main Menu.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Log Off.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:25]]></Time>
<TimeTick>1626375865</TimeTick>
<NodeArgs eType="Replay" icon="608" nRep="14" >
<Disp><![CDATA[Log Off.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Back Office.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:25]]></Time>
<TimeTick>1626375865</TimeTick>
<NodeArgs eType="Replay" icon="608" nRep="15" >
<Disp><![CDATA[Back Office.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Back Office.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:25]]></Time>
<TimeTick>1626375865</TimeTick>
<NodeArgs eType="Replay" icon="608" nRep="17" >
<Disp><![CDATA[Back Office.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:26]]></Time>
<TimeTick>1626375866</TimeTick>
<NodeArgs eType="Replay" icon="609" nRep="19" >
<Disp><![CDATA[Back Office Login.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:26]]></Time>
<TimeTick>1626375866</TimeTick>
<NodeArgs eType="Replay" icon="609" nRep="21" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Back Office Login.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5fc097abb195b0915582818a640b"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:26]]></Time>
<TimeTick>1626375866</TimeTick>
<NodeArgs eType="Replay" icon="609" nRep="23" >
<Disp><![CDATA[Back Office Login.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:26]]></Time>
<TimeTick>1626375866</TimeTick>
<NodeArgs eType="Replay" icon="609" nRep="25" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Override.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:26]]></Time>
<TimeTick>1626375866</TimeTick>
<NodeArgs eType="Replay" icon="608" nRep="26" >
<Disp><![CDATA[Override.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Override.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:26]]></Time>
<TimeTick>1626375866</TimeTick>
<NodeArgs eType="Replay" icon="608" nRep="28" >
<Disp><![CDATA[Override.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:28]]></Time>
<TimeTick>1626375868</TimeTick>
<NodeArgs eType="Replay" icon="608" nRep="29" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:28]]></Time>
<TimeTick>1626375868</TimeTick>
<NodeArgs eType="Replay" icon="608" nRep="31" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Confirm.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:31]]></Time>
<TimeTick>1626375871</TimeTick>
<NodeArgs eType="Replay" icon="608" nRep="32" >
<Disp><![CDATA[Confirm.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:31]]></Time>
<TimeTick>1626375871</TimeTick>
<NodeArgs eType="Replay" icon="608" nRep="34" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[DtvList_2.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#3"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:32]]></Time>
<TimeTick>1626375872</TimeTick>
<NodeArgs eType="Replay" icon="607" nRep="36" >
<Disp><![CDATA[DtvList_2.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[DtvList_2.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#0"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:34]]></Time>
<TimeTick>1626375874</TimeTick>
<NodeArgs eType="Replay" icon="607" nRep="38" >
<Disp><![CDATA[DtvList_2.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:36]]></Time>
<TimeTick>1626375876</TimeTick>
<NodeArgs eType="Replay" icon="608" nRep="40" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Add.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:38]]></Time>
<TimeTick>1626375878</TimeTick>
<NodeArgs eType="Replay" icon="608" nRep="42" >
<Disp><![CDATA[Add.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Search Criteria.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Order/Fulfilment Number"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:38]]></Time>
<TimeTick>1626375878</TimeTick>
<NodeArgs eType="Replay" icon="607" nRep="44" >
<Disp><![CDATA[Search Criteria.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[PosTextField.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["se-300739203"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:40]]></Time>
<TimeTick>1626375880</TimeTick>
<NodeArgs eType="Replay" icon="609" nRep="46" >
<Disp><![CDATA[PosTextField.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="606" nRep="11" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[No orders found error]]></Obj>
<Details ><![CDATA[The No orders found error did not appear as expected]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:46]]></Time>
<TimeTick>1626375886</TimeTick>
<NodeArgs eType="User" icon="610" nRep="47" status="Passed" >
<Disp><![CDATA[No orders found error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:48]]></Time>
<TimeTick>1626375888</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Cancel.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:48]]></Time>
<TimeTick>1626375888</TimeTick>
<NodeArgs eType="Replay" icon="608" nRep="50" >
<Disp><![CDATA[Cancel.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Cancel.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:50]]></Time>
<TimeTick>1626375890</TimeTick>
<NodeArgs eType="Replay" icon="608" nRep="52" >
<Disp><![CDATA[Cancel.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Back_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:52]]></Time>
<TimeTick>1626375892</TimeTick>
<NodeArgs eType="Replay" icon="608" nRep="54" >
<Disp><![CDATA[Back_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Till.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:54]]></Time>
<TimeTick>1626375894</TimeTick>
<NodeArgs eType="Replay" icon="608" nRep="56" >
<Disp><![CDATA[Till.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[7/15/2021 - 20:04:54]]></Time>
<TimeTick>1626375894</TimeTick>
<NodeArgs eType="General" icon="611" nRep="57" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="606" nRep="49" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/15/2021 - 20:04:15" eTime="7/15/2021 - 20:04:54" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="604" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="603" nRep="6" status="Passed" >
<Disp><![CDATA[TC075_ClickAndCollect_TAO_253 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="7/15/2021 - 20:04:13" eTime="7/15/2021 - 20:04:54" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="601" nRep="3" status="Passed" >
<Disp><![CDATA[Test TC075_ClickAndCollect_TAO_253 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>