<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="AO2E2E919R2"><DocLocation><![CDATA[C:\Click And Collect\Automation\Test Scripts\TC022_CC_BackOffice_CollectButton_Ecomm]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[TC022_CC_BackOffice_CollectButton_Ecomm]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="673" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:35]]></Time>
<TimeTick>1626374495</TimeTick>
<NodeArgs eType="Replay" icon="676" nRep="8" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:35]]></Time>
<TimeTick>1626374495</TimeTick>
<NodeArgs eType="Replay" icon="676" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:40]]></Time>
<TimeTick>1626374500</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Main Menu.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:40]]></Time>
<TimeTick>1626374500</TimeTick>
<NodeArgs eType="Replay" icon="678" nRep="12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Main Menu.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Log Off.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:42]]></Time>
<TimeTick>1626374502</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="14" >
<Disp><![CDATA[Log Off.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Back Office.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:42]]></Time>
<TimeTick>1626374502</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="15" >
<Disp><![CDATA[Back Office.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Back Office.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:42]]></Time>
<TimeTick>1626374502</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="17" >
<Disp><![CDATA[Back Office.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:42]]></Time>
<TimeTick>1626374502</TimeTick>
<NodeArgs eType="Replay" icon="680" nRep="19" >
<Disp><![CDATA[Back Office Login.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:42]]></Time>
<TimeTick>1626374502</TimeTick>
<NodeArgs eType="Replay" icon="680" nRep="21" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Back Office Login.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5fc097abb195b0915582818a640b"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:42]]></Time>
<TimeTick>1626374502</TimeTick>
<NodeArgs eType="Replay" icon="680" nRep="23" >
<Disp><![CDATA[Back Office Login.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:42]]></Time>
<TimeTick>1626374502</TimeTick>
<NodeArgs eType="Replay" icon="680" nRep="25" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Override.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:43]]></Time>
<TimeTick>1626374503</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="26" >
<Disp><![CDATA[Override.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Override.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:43]]></Time>
<TimeTick>1626374503</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="28" >
<Disp><![CDATA[Override.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:45]]></Time>
<TimeTick>1626374505</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="29" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:45]]></Time>
<TimeTick>1626374505</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="31" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Confirm.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:47]]></Time>
<TimeTick>1626374507</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="32" >
<Disp><![CDATA[Confirm.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:47]]></Time>
<TimeTick>1626374507</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="34" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[DtvList_2.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#3"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:48]]></Time>
<TimeTick>1626374508</TimeTick>
<NodeArgs eType="Replay" icon="678" nRep="36" >
<Disp><![CDATA[DtvList_2.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[DtvList_2.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#0"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:50]]></Time>
<TimeTick>1626374510</TimeTick>
<NodeArgs eType="Replay" icon="678" nRep="38" >
<Disp><![CDATA[DtvList_2.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:52]]></Time>
<TimeTick>1626374512</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="40" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Add.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:54]]></Time>
<TimeTick>1626374514</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="42" >
<Disp><![CDATA[Add.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Search Criteria.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Order/Fulfilment Number"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:55]]></Time>
<TimeTick>1626374515</TimeTick>
<NodeArgs eType="Replay" icon="678" nRep="44" >
<Disp><![CDATA[Search Criteria.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[PosTextField.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["se-300739204"]]></Details>
<Time><![CDATA[7/15/2021 - 19:41:57]]></Time>
<TimeTick>1626374517</TimeTick>
<NodeArgs eType="Replay" icon="680" nRep="46" >
<Disp><![CDATA[PosTextField.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="677" nRep="11" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[No orders found error]]></Obj>
<Details ><![CDATA[The No orders found error did not appear as expected]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:03]]></Time>
<TimeTick>1626374523</TimeTick>
<NodeArgs eType="User" icon="681" nRep="47" status="Passed" >
<Disp><![CDATA[No orders found error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:05]]></Time>
<TimeTick>1626374525</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Cancel.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:05]]></Time>
<TimeTick>1626374525</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="50" >
<Disp><![CDATA[Cancel.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Cancel.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:07]]></Time>
<TimeTick>1626374527</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="52" >
<Disp><![CDATA[Cancel.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Back_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:09]]></Time>
<TimeTick>1626374529</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="54" >
<Disp><![CDATA[Back_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Till.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:11]]></Time>
<TimeTick>1626374531</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="56" >
<Disp><![CDATA[Till.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:13]]></Time>
<TimeTick>1626374533</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="57" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="677" nRep="49" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:13]]></Time>
<TimeTick>1626374533</TimeTick>
<NodeArgs eType="User" icon="681" nRep="58" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:15]]></Time>
<TimeTick>1626374535</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:15]]></Time>
<TimeTick>1626374535</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="60" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="677" nRep="59" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:15]]></Time>
<TimeTick>1626374535</TimeTick>
<NodeArgs eType="User" icon="681" nRep="61" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:17]]></Time>
<TimeTick>1626374537</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:17]]></Time>
<TimeTick>1626374537</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="63" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="677" nRep="62" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:17]]></Time>
<TimeTick>1626374537</TimeTick>
<NodeArgs eType="User" icon="681" nRep="64" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:19]]></Time>
<TimeTick>1626374539</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:19]]></Time>
<TimeTick>1626374539</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="66" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="677" nRep="65" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:19]]></Time>
<TimeTick>1626374539</TimeTick>
<NodeArgs eType="User" icon="681" nRep="67" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:21]]></Time>
<TimeTick>1626374541</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:21]]></Time>
<TimeTick>1626374541</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="69" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="677" nRep="68" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:21]]></Time>
<TimeTick>1626374541</TimeTick>
<NodeArgs eType="User" icon="681" nRep="70" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:23]]></Time>
<TimeTick>1626374543</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:23]]></Time>
<TimeTick>1626374543</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="72" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="677" nRep="71" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:23]]></Time>
<TimeTick>1626374543</TimeTick>
<NodeArgs eType="User" icon="681" nRep="73" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:25]]></Time>
<TimeTick>1626374545</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:25]]></Time>
<TimeTick>1626374545</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="75" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="677" nRep="74" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:25]]></Time>
<TimeTick>1626374545</TimeTick>
<NodeArgs eType="User" icon="681" nRep="76" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:27]]></Time>
<TimeTick>1626374547</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:27]]></Time>
<TimeTick>1626374547</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="78" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="677" nRep="77" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:27]]></Time>
<TimeTick>1626374547</TimeTick>
<NodeArgs eType="User" icon="681" nRep="79" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:29]]></Time>
<TimeTick>1626374549</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:29]]></Time>
<TimeTick>1626374549</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="81" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="677" nRep="80" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:29]]></Time>
<TimeTick>1626374549</TimeTick>
<NodeArgs eType="User" icon="681" nRep="82" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:31]]></Time>
<TimeTick>1626374551</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:31]]></Time>
<TimeTick>1626374551</TimeTick>
<NodeArgs eType="Replay" icon="679" nRep="84" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="677" nRep="83" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:31]]></Time>
<TimeTick>1626374551</TimeTick>
<NodeArgs eType="User" icon="681" nRep="85" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[7/15/2021 - 19:42:31]]></Time>
<TimeTick>1626374551</TimeTick>
<NodeArgs eType="General" icon="682" nRep="86" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/15/2021 - 19:41:32" eTime="7/15/2021 - 19:42:31" passed="13" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="675" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="674" nRep="6" status="Passed" >
<Disp><![CDATA[TC022_CC_BackOffice_CollectButton_Ecomm Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="7/15/2021 - 19:41:30" eTime="7/15/2021 - 19:42:31" passed="13" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="672" nRep="3" status="Passed" >
<Disp><![CDATA[Test TC022_CC_BackOffice_CollectButton_Ecomm Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>