<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="AO2E2E919R2"><DocLocation><![CDATA[C:\Click And Collect\Automation\Test Scripts\TC_05_CnC_Enquiry Extend order button is disabled]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[TC_05_CnC_Enquiry Extend order button is disabled]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="1175" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Add-in(s) not activated]]></Obj>
<Details plainTxt="False" ><![CDATA[The following add-in(s) were associated with your test, but are not currently loaded: 
Flex.]]></Details>
<Time><![CDATA[7/16/2021 - 5:08:50]]></Time>
<TimeTick>1626408530</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="5" status="Warning" >
<Disp><![CDATA[Add-in(s) not activated]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[Action1]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[7/16/2021 - 5:08:54]]></Time>
<TimeTick>1626408534</TimeTick>
<NodeArgs eType="Replay" icon="1178" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 5:08:58]]></Time>
<TimeTick>1626408538</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Main Menu.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[7/16/2021 - 5:08:58]]></Time>
<TimeTick>1626408538</TimeTick>
<NodeArgs eType="Replay" icon="1180" nRep="12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Main Menu.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Log Off.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:00]]></Time>
<TimeTick>1626408540</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="14" >
<Disp><![CDATA[Log Off.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Back Office.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:02]]></Time>
<TimeTick>1626408542</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="16" >
<Disp><![CDATA[Back Office.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:02]]></Time>
<TimeTick>1626408542</TimeTick>
<NodeArgs eType="Replay" icon="1182" nRep="18" >
<Disp><![CDATA[Back Office Login.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:02]]></Time>
<TimeTick>1626408542</TimeTick>
<NodeArgs eType="Replay" icon="1182" nRep="20" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Back Office Login.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5fb62841df750d5f39c3b3916502"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:02]]></Time>
<TimeTick>1626408542</TimeTick>
<NodeArgs eType="Replay" icon="1182" nRep="22" >
<Disp><![CDATA[Back Office Login.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:02]]></Time>
<TimeTick>1626408542</TimeTick>
<NodeArgs eType="Replay" icon="1182" nRep="24" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Override.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:03]]></Time>
<TimeTick>1626408543</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="25" >
<Disp><![CDATA[Override.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Override.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:03]]></Time>
<TimeTick>1626408543</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="27" >
<Disp><![CDATA[Override.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:05]]></Time>
<TimeTick>1626408545</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="28" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:05]]></Time>
<TimeTick>1626408545</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="30" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Confirm.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:08]]></Time>
<TimeTick>1626408548</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="31" >
<Disp><![CDATA[Confirm.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:08]]></Time>
<TimeTick>1626408548</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="33" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[DtvList.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#3"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:10]]></Time>
<TimeTick>1626408550</TimeTick>
<NodeArgs eType="Replay" icon="1180" nRep="35" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[DtvList.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[DtvList.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#2"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:12]]></Time>
<TimeTick>1626408552</TimeTick>
<NodeArgs eType="Replay" icon="1180" nRep="37" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[DtvList.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Search Criteria.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["All Orders"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:14]]></Time>
<TimeTick>1626408554</TimeTick>
<NodeArgs eType="Replay" icon="1180" nRep="39" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Search Criteria.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Confirm_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:18]]></Time>
<TimeTick>1626408558</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="41" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Confirm_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[DtvList.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#0"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:20]]></Time>
<TimeTick>1626408560</TimeTick>
<NodeArgs eType="Replay" icon="1180" nRep="43" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[DtvList.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:22]]></Time>
<TimeTick>1626408562</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="45" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Extend Order.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:24]]></Time>
<TimeTick>1626408564</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="46" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Extend Order.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="1179" nRep="11" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[Verify Extend Order Button is disabled]]></Obj>
<Details ><![CDATA[Collect Order Button is disabled]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:24]]></Time>
<TimeTick>1626408564</TimeTick>
<NodeArgs eType="User" icon="1183" nRep="47" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Verify Extend Order Button is disabled]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:26]]></Time>
<TimeTick>1626408566</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Back.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:26]]></Time>
<TimeTick>1626408566</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="50" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Back.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Back.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:28]]></Time>
<TimeTick>1626408568</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="52" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Back.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Back_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:30]]></Time>
<TimeTick>1626408570</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="54" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Back_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Back_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:32]]></Time>
<TimeTick>1626408572</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="56" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Back_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:34]]></Time>
<TimeTick>1626408574</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="57" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="1179" nRep="49" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:34]]></Time>
<TimeTick>1626408574</TimeTick>
<NodeArgs eType="User" icon="1183" nRep="58" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:36]]></Time>
<TimeTick>1626408576</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:36]]></Time>
<TimeTick>1626408576</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="60" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="1179" nRep="59" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:36]]></Time>
<TimeTick>1626408576</TimeTick>
<NodeArgs eType="User" icon="1183" nRep="61" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:38]]></Time>
<TimeTick>1626408578</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:38]]></Time>
<TimeTick>1626408578</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="63" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="1179" nRep="62" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:38]]></Time>
<TimeTick>1626408578</TimeTick>
<NodeArgs eType="User" icon="1183" nRep="64" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:40]]></Time>
<TimeTick>1626408580</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:40]]></Time>
<TimeTick>1626408580</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="66" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="1179" nRep="65" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:40]]></Time>
<TimeTick>1626408580</TimeTick>
<NodeArgs eType="User" icon="1183" nRep="67" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:42]]></Time>
<TimeTick>1626408582</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:42]]></Time>
<TimeTick>1626408582</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="69" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="1179" nRep="68" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:42]]></Time>
<TimeTick>1626408582</TimeTick>
<NodeArgs eType="User" icon="1183" nRep="70" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:44]]></Time>
<TimeTick>1626408584</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:44]]></Time>
<TimeTick>1626408584</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="72" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="1179" nRep="71" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:44]]></Time>
<TimeTick>1626408584</TimeTick>
<NodeArgs eType="User" icon="1183" nRep="73" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:46]]></Time>
<TimeTick>1626408586</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:46]]></Time>
<TimeTick>1626408586</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="75" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="1179" nRep="74" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:46]]></Time>
<TimeTick>1626408586</TimeTick>
<NodeArgs eType="User" icon="1183" nRep="76" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:48]]></Time>
<TimeTick>1626408588</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:48]]></Time>
<TimeTick>1626408588</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="78" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="1179" nRep="77" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:48]]></Time>
<TimeTick>1626408588</TimeTick>
<NodeArgs eType="User" icon="1183" nRep="79" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:50]]></Time>
<TimeTick>1626408590</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:50]]></Time>
<TimeTick>1626408590</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="81" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="1179" nRep="80" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:50]]></Time>
<TimeTick>1626408590</TimeTick>
<NodeArgs eType="User" icon="1183" nRep="82" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:52]]></Time>
<TimeTick>1626408592</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:52]]></Time>
<TimeTick>1626408592</TimeTick>
<NodeArgs eType="Replay" icon="1181" nRep="84" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="1179" nRep="83" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:52]]></Time>
<TimeTick>1626408592</TimeTick>
<NodeArgs eType="User" icon="1183" nRep="85" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[7/16/2021 - 5:09:52]]></Time>
<TimeTick>1626408592</TimeTick>
<NodeArgs eType="General" icon="1184" nRep="86" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/16/2021 - 5:08:50" eTime="7/16/2021 - 5:09:52" passed="12" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="1177" nRep="8" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="1176" nRep="7" status="Passed" >
<Disp><![CDATA[TC_05_CnC_Enquiry Extend order button is disabled Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="7/16/2021 - 5:08:48" eTime="7/16/2021 - 5:09:52" passed="12" failed="0" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1174" nRep="3" status="Warning" >
<Disp><![CDATA[Test TC_05_CnC_Enquiry Extend order button is disabled Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>