<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="AO2E2E919R2"><DocLocation><![CDATA[C:\Click And Collect\Automation\Test Scripts\TC080_CC_14_153_ Enquiry order search_CnC]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[TC080_CC_14_153_ Enquiry order search_CnC]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="697" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:43]]></Time>
<TimeTick>1626405943</TimeTick>
<NodeArgs eType="Replay" icon="700" nRep="8" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:43]]></Time>
<TimeTick>1626405943</TimeTick>
<NodeArgs eType="Replay" icon="700" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:47]]></Time>
<TimeTick>1626405947</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Main Menu.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:47]]></Time>
<TimeTick>1626405947</TimeTick>
<NodeArgs eType="Replay" icon="702" nRep="12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Main Menu.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Log Off.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:49]]></Time>
<TimeTick>1626405949</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="14" >
<Disp><![CDATA[Log Off.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Back Office.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:49]]></Time>
<TimeTick>1626405949</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="15" >
<Disp><![CDATA[Back Office.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Back Office.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:49]]></Time>
<TimeTick>1626405949</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="17" >
<Disp><![CDATA[Back Office.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100"]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:50]]></Time>
<TimeTick>1626405950</TimeTick>
<NodeArgs eType="Replay" icon="704" nRep="19" >
<Disp><![CDATA[Back Office Login.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:50]]></Time>
<TimeTick>1626405950</TimeTick>
<NodeArgs eType="Replay" icon="704" nRep="21" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Back Office Login.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5fc097abb195b0915582818a640b"]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:50]]></Time>
<TimeTick>1626405950</TimeTick>
<NodeArgs eType="Replay" icon="704" nRep="23" >
<Disp><![CDATA[Back Office Login.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:50]]></Time>
<TimeTick>1626405950</TimeTick>
<NodeArgs eType="Replay" icon="704" nRep="25" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Override.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:50]]></Time>
<TimeTick>1626405950</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="26" >
<Disp><![CDATA[Override.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Override.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:50]]></Time>
<TimeTick>1626405950</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="28" >
<Disp><![CDATA[Override.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:52]]></Time>
<TimeTick>1626405952</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="29" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:52]]></Time>
<TimeTick>1626405952</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="31" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Confirm.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:55]]></Time>
<TimeTick>1626405955</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="32" >
<Disp><![CDATA[Confirm.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:55]]></Time>
<TimeTick>1626405955</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="34" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[DtvList_2.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#3"]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:56]]></Time>
<TimeTick>1626405956</TimeTick>
<NodeArgs eType="Replay" icon="702" nRep="36" >
<Disp><![CDATA[DtvList_2.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[DtvList_2.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#0"]]></Details>
<Time><![CDATA[7/16/2021 - 4:25:58]]></Time>
<TimeTick>1626405958</TimeTick>
<NodeArgs eType="Replay" icon="702" nRep="38" >
<Disp><![CDATA[DtvList_2.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:00]]></Time>
<TimeTick>1626405960</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="40" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Add.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:03]]></Time>
<TimeTick>1626405963</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="42" >
<Disp><![CDATA[Add.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Search Criteria.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Order/Fulfilment Number"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:06]]></Time>
<TimeTick>1626405966</TimeTick>
<NodeArgs eType="Replay" icon="702" nRep="44" >
<Disp><![CDATA[Search Criteria.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ PosTextField ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["se-300741209"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:10]]></Time>
<TimeTick>1626405970</TimeTick>
<NodeArgs eType="Replay" icon="704" nRep="46" >
<Disp><![CDATA[[ PosTextField ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Add Manually.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:16]]></Time>
<TimeTick>1626405976</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="48" >
<Disp><![CDATA[Add Manually.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:18]]></Time>
<TimeTick>1626405978</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="50" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Customer Name.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Mr"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:20]]></Time>
<TimeTick>1626405980</TimeTick>
<NodeArgs eType="Replay" icon="702" nRep="52" >
<Disp><![CDATA[Customer Name.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[PosTextField.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Test"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:20]]></Time>
<TimeTick>1626405980</TimeTick>
<NodeArgs eType="Replay" icon="704" nRep="54" >
<Disp><![CDATA[PosTextField.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[PosTextField_2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Accepta10"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:20]]></Time>
<TimeTick>1626405980</TimeTick>
<NodeArgs eType="Replay" icon="704" nRep="56" >
<Disp><![CDATA[PosTextField_2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Contact Number.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["07111111111"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:20]]></Time>
<TimeTick>1626405980</TimeTick>
<NodeArgs eType="Replay" icon="704" nRep="58" >
<Disp><![CDATA[Contact Number.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Order/Fulfilment Number.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["se-300741209"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:20]]></Time>
<TimeTick>1626405980</TimeTick>
<NodeArgs eType="Replay" icon="704" nRep="60" >
<Disp><![CDATA[Order/Fulfilment Number.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Courier.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["UK MAIL"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:20]]></Time>
<TimeTick>1626405980</TimeTick>
<NodeArgs eType="Replay" icon="702" nRep="62" >
<Disp><![CDATA[Courier.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Parcel Reference.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["00000074120009"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:23]]></Time>
<TimeTick>1626405983</TimeTick>
<NodeArgs eType="Replay" icon="704" nRep="64" >
<Disp><![CDATA[Parcel Reference.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ Yes ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:42]]></Time>
<TimeTick>1626406002</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="65" >
<Disp><![CDATA[[ Yes ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ Yes ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:42]]></Time>
<TimeTick>1626406002</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="67" >
<Disp><![CDATA[[ Yes ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="701" nRep="11" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[Add Order]]></Obj>
<Details ><![CDATA[Order has been added successfully, hence Passed]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:42]]></Time>
<TimeTick>1626406002</TimeTick>
<NodeArgs eType="User" icon="705" nRep="68" status="Passed" >
<Disp><![CDATA[Add Order]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:46]]></Time>
<TimeTick>1626406006</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Till.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:46]]></Time>
<TimeTick>1626406006</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="71" >
<Disp><![CDATA[Till.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Additional Options.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:48]]></Time>
<TimeTick>1626406008</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="73" >
<Disp><![CDATA[Additional Options.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Click & Collect.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:50]]></Time>
<TimeTick>1626406010</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="75" >
<Disp><![CDATA[Click & Collect.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Collect.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:52]]></Time>
<TimeTick>1626406012</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="77" >
<Disp><![CDATA[Collect.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Search Criteria.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Order/Fulfilment Number"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:54]]></Time>
<TimeTick>1626406014</TimeTick>
<NodeArgs eType="Replay" icon="702" nRep="79" >
<Disp><![CDATA[Search Criteria.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Input Search Criteria.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["se-300741209"]]></Details>
<Time><![CDATA[7/16/2021 - 4:26:56]]></Time>
<TimeTick>1626406016</TimeTick>
<NodeArgs eType="Replay" icon="704" nRep="81" >
<Disp><![CDATA[Input Search Criteria.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:15]]></Time>
<TimeTick>1626406035</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="82" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="701" nRep="70" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:15]]></Time>
<TimeTick>1626406035</TimeTick>
<NodeArgs eType="User" icon="705" nRep="83" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:17]]></Time>
<TimeTick>1626406037</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:17]]></Time>
<TimeTick>1626406037</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="85" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="701" nRep="84" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:17]]></Time>
<TimeTick>1626406037</TimeTick>
<NodeArgs eType="User" icon="705" nRep="86" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:19]]></Time>
<TimeTick>1626406039</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:19]]></Time>
<TimeTick>1626406039</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="88" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="701" nRep="87" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:19]]></Time>
<TimeTick>1626406039</TimeTick>
<NodeArgs eType="User" icon="705" nRep="89" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:21]]></Time>
<TimeTick>1626406041</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:21]]></Time>
<TimeTick>1626406041</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="91" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="701" nRep="90" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:21]]></Time>
<TimeTick>1626406041</TimeTick>
<NodeArgs eType="User" icon="705" nRep="92" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:23]]></Time>
<TimeTick>1626406043</TimeTick>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:23]]></Time>
<TimeTick>1626406043</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="94" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="701" nRep="93" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:23]]></Time>
<TimeTick>1626406043</TimeTick>
<NodeArgs eType="User" icon="705" nRep="95" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:25]]></Time>
<TimeTick>1626406045</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:25]]></Time>
<TimeTick>1626406045</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="97" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="701" nRep="96" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:25]]></Time>
<TimeTick>1626406045</TimeTick>
<NodeArgs eType="User" icon="705" nRep="98" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:27]]></Time>
<TimeTick>1626406047</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:27]]></Time>
<TimeTick>1626406047</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="100" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="701" nRep="99" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:27]]></Time>
<TimeTick>1626406047</TimeTick>
<NodeArgs eType="User" icon="705" nRep="101" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:29]]></Time>
<TimeTick>1626406049</TimeTick>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:29]]></Time>
<TimeTick>1626406049</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="103" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="701" nRep="102" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:29]]></Time>
<TimeTick>1626406049</TimeTick>
<NodeArgs eType="User" icon="705" nRep="104" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:31]]></Time>
<TimeTick>1626406051</TimeTick>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:31]]></Time>
<TimeTick>1626406051</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="106" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="701" nRep="105" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:31]]></Time>
<TimeTick>1626406051</TimeTick>
<NodeArgs eType="User" icon="705" nRep="107" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:33]]></Time>
<TimeTick>1626406053</TimeTick>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:33]]></Time>
<TimeTick>1626406053</TimeTick>
<NodeArgs eType="Replay" icon="703" nRep="109" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="701" nRep="108" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:33]]></Time>
<TimeTick>1626406053</TimeTick>
<NodeArgs eType="User" icon="705" nRep="110" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[7/16/2021 - 4:27:33]]></Time>
<TimeTick>1626406053</TimeTick>
<NodeArgs eType="General" icon="706" nRep="111" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/16/2021 - 4:25:40" eTime="7/16/2021 - 4:27:33" passed="13" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="699" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="698" nRep="6" status="Passed" >
<Disp><![CDATA[TC080_CC_14_153_ Enquiry order search_CnC Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>